kind: Service
apiVersion: v1
metadata:
  name: csi-gce-pd
  labels:
    app: csi-gce-pd
spec:
  selector:
    app: csi-gce-pd
  ports:
    - name: dummy
      port: 12345

---

kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  name: csi-gce-pd-driver
spec:
  serviceName: "csi-gce-pd"
  replicas: 1
  selector:
    matchLabels:
      app: csi-gce-pd-driver
  template:
    metadata:
      labels:
        app: csi-gce-pd-driver
    spec:
      serviceAccount: csi-gce-pd
      containers:
        - name: csi-external-provisioner
          imagePullPolicy: Always
          image: docker.io/k8scsi/csi-provisioner:0.1
          args:
            - "--v=5"
            - "--provisioner=csi-gce-pd"
            - "--csi-address=$(ADDRESS)"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
        - name: csi-attacher
          imagePullPolicy: Always
          image: gcr.io/dyzz-csi-staging/csi/external-attacher:latest
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
        - name: gce-driver
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true
          imagePullPolicy: Always
          image: gcr.io/dyzz-csi-staging/csi/gce-driver:latest
          args:
            - "--v=5"
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--nodeid=$(KUBE_NODE_NAME)"
            - "--project=dyzz-test"
          env:
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
      volumes:
        - name: socket-dir
          emptyDir: {}
